# Generated by Django 5.0.6 on 2025-07-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
        migrations.AddField(
            model_name='order',
            name='product_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
